---
title: "Bivariate Viz"
execute:
  echo: true
  warning: false
  error: false

format: 
  html: 
    code-fold: true
---




```{r}
#| fig-alt: "The title of this graph is, California: Income vs. Standardized Math Test Scores. The x-axis represents Income and the y axis represents Math Test Score. This graph was created in 2025 by Nolan Rittenberg"

library(tidyverse)

CA_Test_Scores = read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/AER/CASchools.csv")

ggplot(CA_Test_Scores, aes(x = income, y = math)) + 
  geom_point() + 
  geom_smooth() +
  theme_bw() +
  labs(title = "California: Income vs. Standardized Math Test Scores",
       x = "Income",
       y = "Math Test Score",
       caption = "By: Nolan Rittenberg | 2025\nsource: CASchools dataset from the AER package. Accessed via Rdatasets: Vincent Arel-Bundock (https://vincentarelbundock.github.io/Rdatasets)") +
  theme(
    panel.background = element_rect(fill = "white", color = "white"),
    plot.background = element_rect(fill = "white", color = "white"),
    legend.background = element_rect(fill = "white", color = "white"),
    plot.caption = element_text(size = 7, hjust = 0),
    plot.title = element_text(size = 12, hjust = 0.5)
    )
  

```



```{r}
library("mosaic")
library("mosaicData")
library("fivethirtyeight")


data(bechdel)
new_bechdel <- bechdel |>
  mutate(clean_test = factor(clean_test, c("nowomen", "notalk", "men", "dubious", "ok"))) |>
  mutate(half_decades = cut(year, breaks = seq(1969, 2014, by = 5)))


ggplot(new_bechdel, aes(x = half_decades, fill = clean_test)) + 
  geom_bar(position = "dodge") +
  scale_color_viridis_b() +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(size = 12, hjust = 0.5),
    plot.caption = element_text(hjust = 0, size = 7),

) +
  labs(
    title = "New Bechdel Test Over The Past 45 Years",
    x = "Years",
    y = "Number of Movies",
    fill = "Clean Test",
    caption = "By: Nolan Rittenberg | 2025\nFiveThirtyEight — 'The Dollar-And-Cents Case Against Hollywood’s Exclusion of Women'")
```











