---
title: "Project1_choropleth_map"
format: html
---

```{r}

library(tidyverse)
library(sf)
library(rnaturalearth)

```



```{r}

covid_in_italy <- read_csv("~/Documents/portfolio-NolanRittenberg/bw/covid19_italy_province.csv")

covid_in_italy_per_region <- covid_in_italy |>
  group_by(RegionName) |>
  summarise(region_cases = n())
  
```

```{r}
italy_shape_file <- read_sf("georef-italy-provincia/georef-italy-provincia-millesime.shp")

italy_map <- ne_states(returnclass = "sf", country = "Italy")

covid_in_italy_per_shape <- italy_shape_file |>
  left_join(covid_in_italy_per_region, join_by(reg_name == RegionName))
  


  
ggplot(covid_in_italy_per_shape) + 
  geom_sf(
    aes(fill = region_cases)
  ) +
  scale_fill_gradient(
    low = "pink",
    high = "darkred",
    name = "Total Number of Covid Cases"
  ) + 
  labs(title = "Amount of Covid Cases Per Province In Italy (2022)", 
       subtitle = "Grey = N/A", 
       caption = "By: Nolan Rittenberg") + 
  theme_void() + 
  theme(
    plot.title = element_text(hjust = .5, face = "bold"), 
    plot.subtitle = element_text(hjust = .5), 
    plot.caption = element_text(hjust = .5),
    plot.margin = margin(t = 10, r = 10, b = 20, l = 10)
  )


# region_cases are NA for the provinces, Bolzano and Trento. This dataset does not have data for the covid cases in Bolzano and Trento. 

```




























